name: Cached node_modules
description: A GitHub Action to cache node_modules
author: AnnAngela

branding:
  icon: save
  color: purple

inputs:
  cacheKey:
    description: The key of the cache
    required: false
    default: cached_node-modules:{OS_NAME}:node@{NODE_VERSION_MAJOR}_{NODE_ARCH}:npm@{NPM_VERSION_MAJOR}:package-lock@{LOCKFILE_GIT_COMMIT_SHORT}{CUSTOM_VARIABLE}
  customVariable:
    description: The custom variable to insert to the cache key
    required: false
    default: ""
  command:
    description: The command to run for installing dependencies
    required: false
    default: npm ci
  cwd:
    description: The working directory
    required: false
    default: .
  lockfilePath:
    description: The path to the lockfile
    required: false
    default: package-lock.json
  packageJsonPath:
    description: The path to the package.json
    required: false
    default: package.json
  networkErrorRetryTime:
    description: The retry time when network error occurs while running the command, `0` means no retry
    required: false
    default: "3"
  githubToken:
    description: The GitHub token
    required: false
    default: ${{ github.token }}

outputs:
  cacheKey:
    description: The parsed cacheKey
  variables:
    description: A JSON string contains all the variables used in `cacheKey`
  cache-hit:
    description: Whether the cache is hit

runs:
  using: node20
  main: dist/index.js
