import fs from "node:fs";
import path from "node:path";
import YAML from "yaml";
import jsonModule from "./jsonModule.js";
import mkdtmp from "./mkdtmp.js";

type dependencyType = {
    dev: true;
    optional?: false;
    devOptional?: false;
} | {
    dev?: false;
    optional: true;
    devOptional?: false;
} | {
    dev?: false;
    optional?: false;
    devOptional: true;
} | {
    dev?: false;
    optional?: false;
    devOptional?: false;
};

/**
 * @TODO Unfinished
 */
type packageDescriptor = {
    version: string;
    integrity: string;
    resolved: string;
    link?: false;
    bundled?: boolean;
    requires?: Record<string, string>;
    dependencies?: Record<string, packageDescriptor>;
} & dependencyType | {
    version: string;
    integrity: string;
    inBundle: true;
} & dependencyType | {
    resolved: string;
    link: true;
};

/**
 * V3
 */
interface packageLockJSON {
    name: string;
    version: string;
    lockfileVersion: 3;
    requires?: boolean;
    packages?: {
        "": packageDescriptor;
        [moduleName: string]: packageDescriptor;
    };
}

const prepare = async (lockfilePath: string, lockfileParsedPath: path.ParsedPath, content?: string) => {
    console.info(`Found ${lockfileParsedPath.base} as lockfile, copy to tmp dir and remove unnecessary fields...`);
    const tmpdir = await mkdtmp();
    const newLockfilePath = path.join(tmpdir, lockfileParsedPath.base);
    console.info("New lockfilePath:", newLockfilePath);
    if (content !== undefined) {
        await fs.promises.writeFile(newLockfilePath, content, "utf-8");
    } else {
        await fs.promises.cp(lockfilePath, newLockfilePath, { force: true });
    }
    return { tmpdir, newLockfilePath };
};

const keptKeys = {
    packageLock: [
        "lockfileVersion",
        "packages",
    ],
};

export const packageLockHandler = async (lockfilePath: string, lockfileParsedPath: path.ParsedPath) => {
    const { tmpdir, newLockfilePath } = await prepare(lockfilePath, lockfileParsedPath);
    const lockfile = await jsonModule.readFile(newLockfilePath) as packageLockJSON;
    const keys = Object.keys(lockfile);
    for (const key of keys) {
        if (!keptKeys.packageLock.includes(key)) {
            Reflect.deleteProperty(lockfile, key);
        }
    }
    if (lockfile.packages) {
        Reflect.deleteProperty(lockfile.packages, "");
    }
    return { tmpdir, lockfileContent: JSON.stringify(lockfile) };
};

/**
 * Handler for pnpm-lock.yaml.
 *
 * pnpm-lock.yaml is a YAML file with the following key sections:
 * - lockfileVersion: the lockfile format version
 * - importers: workspace package dependency declarations
 * - packages: resolved packages with version and integrity info
 * - snapshots: auto-generated dependency topology (stripped — redundant with packages)
 * - time: package publish timestamps (stripped — not relevant for hash)
 *
 * @see https://github.com/pnpm/pnpm/blob/main/lockfile/fs/README.md
 */
export const pnpmLockHandler = async (lockfilePath: string, lockfileParsedPath: path.ParsedPath) => {
    const { tmpdir, newLockfilePath } = await prepare(lockfilePath, lockfileParsedPath);
    const content = await fs.promises.readFile(newLockfilePath, "utf-8");
    let parsed: Record<string, unknown>;
    try {
        // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
        const raw = YAML.parse(content);
        if (typeof raw !== "object" || raw === null || Array.isArray(raw)) {
            throw new Error(`Failed to parse pnpm-lock.yaml: expected an object, got ${typeof raw}`);
        }
        parsed = raw as Record<string, unknown>;
    } catch (cause) {
        // YAML.parse always throws Error instances, and line 114 throws a new Error as well.
        throw new Error(`Failed to parse pnpm-lock.yaml at "${lockfilePath}": ${(cause as Error).message}`, {
            cause,
        });
    }
    // Strip snapshots and time fields — these are auto-generated and do not
    // reflect dependency changes that aren't already captured in packages.
    Reflect.deleteProperty(parsed, "snapshots");
    Reflect.deleteProperty(parsed, "time");
    return { tmpdir, lockfileContent: YAML.stringify(parsed) };
};

/**
 * Handler for Yarn Classic v1 yarn.lock.
 *
 * Yarn Classic lockfiles begin with header comments that are not relevant
 * to dependency resolution:
 *   # THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
 *   # yarn lockfile v1
 *
 * This handler strips those comments, leaving the package entries intact.
 * The format is NOT standard YAML — it uses a custom indented key-value
 * format — so we perform text-level processing rather than parsing.
 *
 * @see https://classic.yarnpkg.com/en/docs/yarn-lock
 */
export const yarnClassicLockHandler = async (lockfilePath: string, lockfileParsedPath: path.ParsedPath, content?: string) => {
    const { tmpdir, newLockfilePath } = await prepare(lockfilePath, lockfileParsedPath, content);
    const fileContent = content ?? await fs.promises.readFile(newLockfilePath, "utf-8");
    const lines = fileContent.split("\n");
    // Strip the two header comment lines that Yarn Classic always generates.
    // These lines are deterministic for a given Yarn version but do not
    // reflect any change in the actual resolved dependency tree.
    const filteredLines = lines.filter((line) =>
        !line.startsWith("# yarn lockfile v1")
        && !line.includes("THIS IS AN AUTOGENERATED FILE"),
    );
    return { tmpdir, lockfileContent: filteredLines.join("\n") };
};

/**
 * Handler for Yarn Berry (v2/v3/v4) yarn.lock.
 *
 * Yarn Berry lockfiles are pure YAML with a top-level __metadata key
 * containing the lockfile version and internal cacheKey. These metadata
 * fields change when Yarn version changes but do not reflect dependency
 * changes, so they are stripped.
 *
 * The header comment line "# This file is generated by running..." is also
 * stripped — it is auto-generated and varies between Yarn versions.
 *
 * @see https://yarnpkg.com/advanced/error-codes (lockfile format)
 * @see https://github.com/yarnpkg/berry
 */
export const yarnBerryLockHandler = async (lockfilePath: string, lockfileParsedPath: path.ParsedPath, content?: string) => {
    const { tmpdir, newLockfilePath } = await prepare(lockfilePath, lockfileParsedPath, content);
    const fileContent = content ?? await fs.promises.readFile(newLockfilePath, "utf-8");
    let parsed: Record<string, unknown>;
    try {
        // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
        const raw = YAML.parse(fileContent);
        if (typeof raw !== "object" || raw === null || Array.isArray(raw)) {
            throw new Error(`Failed to parse yarn.lock (Berry): expected an object, got ${typeof raw}`);
        }
        parsed = raw as Record<string, unknown>;
    } catch (cause) {
        throw new Error(`Failed to parse yarn.lock at "${lockfilePath}": ${(cause as Error).message}`, {
            cause,
        });
    }
    // __metadata contains the lockfile format version and an internal cacheKey.
    // Both are Yarn-version-dependent and do not reflect dependency changes.
    Reflect.deleteProperty(parsed, "__metadata");
    return { tmpdir, lockfileContent: YAML.stringify(parsed) };
};
