name: linter

on:
  push:
    paths:
      - src/**/*
      - .*.yaml
      - eslint.config.js
      - .github/workflows/linter.yaml
      - package.json
      - package-lock.json
      - vitest.config.ts
  merge_group:
  pull_request:
    paths:
      - src/**/*
      - .*.yaml
      - eslint.config.js
      - .github/workflows/linter.yaml
      - package.json
      - package-lock.json
      - vitest.config.ts
  workflow_dispatch:
  schedule:
    - cron: 0 23 * * * # Every 07:00 CST

concurrency:
  group: ${{ github.workflow_ref }}-${{ github.ref }}

permissions:
  contents: read
  actions: write

jobs:
  linter_test:
    name: Lint & test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          show-progress: false
      - name: Use Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v6
        with:
          node-version: lts/*
          check-latest: true
          cache: npm

      - name: Installing the dependencies
        uses: AnnAngela/cached_node-modules@095ea9ae366bc4a18c0f653aed2008d35660317d # v6.0.1
        with:
          command: npm run ci

      - name: Check environment
        run: npx eslint --env-info
      - name: Run eslint
        run: npm run lint:check-ci
      - name: Run tests
        run: npm run test
      - name: Test packaging
        run: npm run package
      - name: Verify build output
        run: |
          node --check ./dist/index.js && echo "dist/index.js is valid JavaScript."
          node --check ./dist/post.js && echo "dist/post.js is valid JavaScript."
      - name: Upload build metafile
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: esbuild-metafiles
          path: .cache/*-meta.json
